Sprint 5/issue 50#user extra information form component
BrightCoders-Institute/proyecto-final-team1a pull request #100
Opened 2023-09-06 04:16 UTC by FebernalGober

# Description

Logic of the components working:
Address receives the address, DateSelector the date of birth and PerfilPhoto brings a photo from the gallery to put it on the profile

the cancel button restarts the form

The Sign Up button submits the form (Logic with Firebase pending)

2023-09-06 04:45 UTC, BrandonVG requested changes
Use eslint and prettier on your files

2023-09-06 04:45 UTC, BrandonVG commented on renta_facil_colima/src/View/Screens/ExtraInfo.jsx
> +    console.log('Formulario enviado con los siguientes valores:', values);
Remove console.log

2023-09-06 04:45 UTC, BrandonVG commented on renta_facil_colima/src/View/Screens/ExtraInfo.jsx
> +                      onChange={date => form.setFieldValue('birthday', date)} // Función para actualizar el valor
Remove comments

2023-09-06 04:45 UTC, BrandonVG commented on renta_facil_colima/src/View/components/DatePicker.jsx
FIle name should be the same as component name

2023-09-06 04:45 UTC, BrandonVG commented on renta_facil_colima/src/View/components/DatePicker.jsx
> +  };
This data is not going anywhere, you are not sending it to any parent or anything else

2023-09-06 04:45 UTC, BrandonVG commented on renta_facil_colima/src/View/Screens/ExtraInfo.jsx
> +                      onChange={date => form.setFieldValue('birthday', date)} // Función para actualizar el valor
In your component you don't receive those props

2023-09-06 04:45 UTC, BrandonVG commented on renta_facil_colima/src/View/components/PerfilPhoto.jsx
> +      console.log('Ruta de la imagen seleccionada:', uri);
Remove console.log

2023-09-06 04:45 UTC, BrandonVG commented on renta_facil_colima/src/hooks/ExtraInfoState.js
> +    profilePicture: Yup.string().notRequired('Profile Picture field can not be empty'),
if it is notRequired your text is wrong

2023-09-06 04:45 UTC, BrandonVG commented on renta_facil_colima/src/styles/DataPickerStyle.js
> +const styles = StyleSheet.create({
"Styles" as a name is very ambiguous, also, names should be descriptive, also is a very different name in comparison to file name

2023-09-06 04:45 UTC, BrandonVG commented on renta_facil_colima/src/styles/ExtraInfoStyle.js
Fix indentation and remove unnecessary spaces

2023-09-06 19:49 UTC, AlbertoG22 approved these changes

2023-09-06 20:11 UTC, Lizzflores approved these changes

2023-09-06 23:08 UTC, Tole15 approved these changes

2023-09-07 23:41 UTC, BrandonVG approved these changes

2023-09-08 00:41 UTC, merged