Splash and Main Screen
BrightCoders-Institute/proyecto-final-team1a pull request #34
Opened 2023-08-08 23:33 UTC by FebernalGober

Main screen screens were created

In Splash, code was used directly instead of some library

for the main screen the reusable components LogoRFC and BasicButton were used

2023-08-08 23:51 UTC, BrandonVG requested changes

2023-08-08 23:51 UTC, BrandonVG commented on renta_facil_colima/App.jsx
Restore the file content

2023-08-09 00:59 UTC, Axw3ll requested changes
Restore the file's content.The right thing to do is resolve conflicts.

2023-08-09 01:35 UTC, Tole15 requested changes
Restore App.jsx and delete comments on any code u have.
![image](https://github.com/BrightCoders-Institute/proyecto-final-team1a/assets/129608820/fea6f084-a67a-4797-ba04-26c7900804d3)

2023-08-09 01:44 UTC, DerekAyala requested changes

2023-08-09 01:44 UTC, DerekAyala commented on renta_facil_colima/App.jsx
Restore the file's content and use .tsx

2023-08-09 01:44 UTC, DerekAyala commented on renta_facil_colima/src/View/components/SplashScreen.jsx
keep the styles on another file

2023-08-10 01:36 UTC, BrandonVG approved these changes

2023-08-10 01:36 UTC, Axw3ll approved these changes

2023-08-10 02:16 UTC, Tole15 approved these changes
Nice Fix!
![image](https://github.com/BrightCoders-Institute/proyecto-final-team1a/assets/129608820/be443797-8702-4cc5-b59c-3f41df220203)

2023-08-10 21:52 UTC, DerekAyala approved these changes

2023-08-10 22:02 UTC, merged