Hook to call houses by UID
BrightCoders-Institute/proyecto-final-team1a pull request #94
Opened 2023-08-30 00:33 UTC by FebernalGober

Hook to call the user's houses using their UID to get only their houses

# Description
Hook to call the user's houses using their UID to get only their houses

2023-08-30 00:37 UTC, DerekAyala approved these changes

2023-08-31 00:24 UTC, BrandonVG requested changes

2023-08-31 00:24 UTC, BrandonVG commented on renta_facil_colima/src/hooks/GetMyHousesFromFirebase.js
> +  };
We already have this function in other hook, remove it from here

2023-08-31 00:24 UTC, BrandonVG commented on renta_facil_colima/src/hooks/GetMyHousesFromFirebase.js
> +  };
We talked about to migrate all hooks  firebase firestore hooks from firebase package to react-native-firebase/firestore and create new with react-native-firebase/firestore, please change the package [as we have in our other hooks on main](https://github.com/BrightCoders-Institute/proyecto-final-team1a/blob/main/renta_facil_colima/src/hooks/GetDataFromFirebase.js)

2023-08-31 00:25 UTC, BrandonVG commented on renta_facil_colima/src/hooks/GetMyHousesFromFirebase.js
> +  };
![image](https://github.com/BrightCoders-Institute/proyecto-final-team1a/assets/54459465/de775ff7-ef97-4cfd-b268-d736e5fb2a61)

2023-09-01 05:06 UTC, closed without merging